### ISSUE TITLE
After fresh Shoko install and first run added folders are not scanned

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/Shoko-WebUI#962] opened 2024-08-10 11:13 UTC
I installed shoko, went thru first run wizard, loved the process and visuals (great job), added import folder thru it and when I end up inside webui shoko downloaded few images from anidb and nothing else. 
It did not start scan on first folder that I added - I unchecked "watch for files" and drop set on None. 

If this is intended behaviour maybe a one time pop up or information would be helpful.

**Comment by ElementalCrisis** [comment] 2024-08-10 15:23
Intended behavior but maybe we can execute Run Import when you close the Welcome Prompt or add a button for it.

**Comment by harshithmohan** [comment] 2024-08-10 15:36
We can just add a Run Import call when we redirect from first run to dashboard. I think we should do it because majority would expect the import to happen after finishing setup

**Comment by harshithmohan** [comment] 2024-08-10 17:24
Fixed in daily aka next stable. Web UI will call run import on finishing first run setup

**Closed by harshithmohan** 2024-08-10 17:24 UTC
Labels: Enhancement - Feature Improvement, By Design
